name = "vendora-backend"
main = "src/index.ts"
compatibility_date = "2025-02-01"

[[d1_databases]]
binding = "DB"
database_name = "vendora-db"
database_id = ""

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "vendora-db"
database_id = ""

[env.staging]
[[env.staging.d1_databases]]
binding = "DB"
database_name = "vendora-db-staging"
database_id = ""
